name: sudoku
description: Sudoku in Flutter, drawn with CustomPainter.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_native_splash: ^2.4.8
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/splash.png            # your 600x500 image; used on Android ≤11 and iOS
  android_12:
    image: assets/splash_android12.png
    color: "#FFFFFF"
    color_dark: "#121212"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/splash.png
    - assets/splash_android12.png
